DELETE FROM Part_RepairJob;
DELETE FROM RepairJob;
DELETE FROM Log;
DELETE FROM RegularCustomer;
DELETE FROM Mechanic;
DELETE FROM Problem;
DELETE FROM Part;
INSERT INTO RegularCustomer VALUES ('Smith', '4085551212', 'email@example.com', 'San Jose');
INSERT INTO RegularCustomer VALUES ('Jones', '4085554444', 'email@example.com', 'New York');
INSERT INTO RegularCustomer VALUES ('Clark', '4083331212', 'email@example.com', 'Houston');
INSERT INTO RegularCustomer VALUES ('Chen', '4086661212', 'email@example.com', 'Chicago');
INSERT INTO Problem VALUES ('1', 'transmission problem');
INSERT INTO Problem VALUES ('2', 'wheel alignment');
INSERT INTO Mechanic VALUES ('1', 'Grant', '4082469554', 20);
INSERT INTO Mechanic VALUES ('2', 'Bloggs', '4087481057', 20);
INSERT INTO RepairJob (repairjobid, timein, licensenumber, model, address, employeeid) VALUES ('1', TO_TIMESTAMP('2019/03/08', 'yyyy/mm/dd'), '11111111', 'Prius', 'San Jose', '1');
INSERT INTO RepairJob (repairjobid, timein, licensenumber, model, address, employeeid) VALUES ('2', TO_TIMESTAMP('2019/03/09', 'yyyy/mm/dd'), '22222222', 'Prius', 'New York', '2');
INSERT INTO RepairJob (repairjobid, timein, licensenumber, model, address, employeeid) VALUES ('3', SYSTIMESTAMP, '33333333', 'Prius', 'Houston', '2');
INSERT INTO RepairJob (repairjobid, timein, licensenumber, model, address, employeeid) VALUES ('4', TO_TIMESTAMP('2019/03/10', 'yyyy/mm/dd'), '44444444', 'Prius', 'Chicago', '2');
INSERT INTO RepairJob (repairjobid, timein, licensenumber, model, address, employeeid) VALUES ('5', SYSTIMESTAMP, '44444444', 'Prius', 'Chicago', '2');
UPDATE RepairJob SET laborhours = 1 WHERE repairjobid = '1';
UPDATE RepairJob SET laborhours = 1 WHERE repairjobid = '2';
UPDATE RepairJob SET laborhours = 1 WHERE repairjobid = '3';
UPDATE RepairJob SET laborhours = 1 WHERE repairjobid = '4';
UPDATE RepairJob SET laborhours = 1 WHERE repairjobid = '5';
UPDATE RepairJob SET problemid = '1' WHERE repairjobid = '1';
UPDATE RepairJob SET problemid = '2' WHERE repairjobid = '2';
UPDATE RepairJob SET problemid = '1' WHERE repairjobid = '3';
UPDATE RepairJob SET problemid = '2' WHERE repairjobid = '4';
UPDATE RepairJob SET problemid = '2' WHERE repairjobid = '5';
INSERT INTO Part VALUES ('1', 'tire', 50);
INSERT INTO Part VALUES ('2', 'wheel', 50);
INSERT INTO Part_RepairJob VALUES ('1', '1');
INSERT INTO Part_RepairJob VALUES ('2', '2');
INSERT INTO Part_RepairJob VALUES ('1', '3');
INSERT INTO Part_RepairJob VALUES ('2', '3');
INSERT INTO Part_RepairJob VALUES ('1', '5');
INSERT INTO Part_RepairJob VALUES ('2', '5');
